name: Deploy Web Server Only

on:
  # This allows you to click a "Run Workflow" button in GitHub manually
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1

    - name: Trigger Deploy on Web Server via SSM
      run: |
        aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Name,Values=web-server" \
          --comment "Deploying new version manually pushed by user" \
          --parameters 'commands=[
            "aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 990060748140.dkr.ecr.ap-southeast-1.amazonaws.com",
            "docker pull 990060748140.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/final-project-mohdadlijaaffar:latest",
            "docker stop my-app || true",
            "docker rm my-app || true",
            "docker run -d --restart always --name my-app -p 80:80 990060748140.dkr.ecr.ap-southeast-1.amazonaws.com/devops-bootcamp/final-project-mohdadlijaaffar:latest"
          ]'